### ISSUE TITLE
Unending stream of "Process (pid 1) got signal 11" on 5.7-stable i386 flashrd 1.9

### ISSUE THREAD

**Issue by bconway** [yellowman/flashrd#30]
Summary: fresh build with 5.7-stable fails to boot with ending stream of:
Process (pid 1) got signal 11

Build host: 5.7-stable i386 (post SSL and X.org fixes, running without issue)

Base dir consists of:
base57.tgz
man57.tgz
xbase57.tgz
./usr/share/sysmerge/etc.tgz (from untarred base57)
./usr/share/sysmerge/xetc.tgz (from untarred xbase57)

flashrd command: ./flashrd -l 3700000 /usr/fdest

Image was **not** modified by cfgflashrd, only manually mounted to do serial redirection for logging in flash/etc/boot. Verified that an unmodified image does the same thing.

dmesg:
-- OpenBSD/i386 BOOT 3.26
com0: changing speed to 19200 baud in 5 seconds, change your terminal to match!

com0: 19200 baud
boot>
booting hd0a:/bsd: 9288676+476196 [72+344464+330487]=0x9f4e74
entry point at 0x200120

[ using 675436 bytes of bsd ELF symbol table ]
Copyright (c) 1982, 1986, 1989, 1991, 1993
        The Regents of the University of California.  All rights reserved.
Copyright (c) 1995-2015 OpenBSD. All rights reserved.  http://www.OpenBSD.org

OpenBSD 5.7 (FLASHRD) #0: Tue Mar 24 02:59:43 UTC 2015
    root@buildi386.int.example.com:/usr/src/sys/arch/i386/compile/FLASHRD
cpu0: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz ("GenuineIntel" 686-class) 2.31 GHz
cpu0: FPU,V86,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,MMX,FXSR,SSE,SSE2,NX
E,LONG,SSE3,MWAIT,SSSE3,LAHF,PERF
real mem  = 267862016 (255MB)
avail mem = 252313600 (240MB)
mpath0 at root
scsibus0 at mpath0: 256 targets
mainbus0 at root
bios0 at mainbus0: date 06/23/99, BIOS32 rev. 0 @ 0xfda00, SMBIOS rev. 2.5 @ 0xe1000 (10 entries)
bios0: vendor innotek GmbH version "VirtualBox" date 12/01/2006
bios0: innotek GmbH VirtualBox
acpi0 at bios0: rev 2
acpi0: sleep states S0 S5
acpi0: tables DSDT FACP APIC SSDT
acpi0: wakeup devices
acpitimer0 at acpi0: 3579545 Hz, 32 bits
acpimadt0 at acpi0 addr 0xfee00000: PC-AT compat
cpu0 at mainbus0: apid 0 (boot processor)
mtrr: CPU supports MTRRs but not enabled by BIOS
cpu0: apic clock running at 1000MHz
ioapic0 at mainbus0: apid 1 pa 0xfec00000, version 11, 24 pins
acpiprt0 at acpi0: bus 0 (PCI0)
acpicpu0 at acpi0
acpibat0 at acpi0: BAT0 model "1" serial 0 type VBOX oem "innotek"
acpiac0 at acpi0: AC unit online
acpivideo at acpi0 not configured
bios0: ROM list: 0xc0000/0x8000 0xe2000/0xd400
pci0 at mainbus0 bus 0: configuration mode 1 (bios)
pchb0 at pci0 dev 0 function 0 "Intel 82441FX" rev 0x02
pcib0 at pci0 dev 1 function 0 "Intel 82371SB ISA" rev 0x00
vga1 at pci0 dev 2 function 0 "InnoTek VirtualBox Graphics Adapter" rev 0x00
vga1: aperture needed
wsdisplay0 at vga1 mux 1: console (80x25, vt100 emulation)
wsdisplay0: screen 1-5 added (80x25, vt100 emulation)
em0 at pci0 dev 3 function 0 "Intel 82540EM" rev 0x02: apic 1 int 19, address 08:00:27:e2:d0:05
"InnoTek VirtualBox Guest Service" rev 0x00 at pci0 dev 4 function 0 not configured
piixpm0 at pci0 dev 7 function 0 "Intel 82371AB Power" rev 0x08: SMBus disabled
ahci0 at pci0 dev 13 function 0 "Intel 82801HBM AHCI" rev 0x02: apic 1 int 21, AHCI 1.1
ahci0: device on port 0 didn't come ready, TFD: 0x171<ERR>
scsibus1 at ahci0: 32 targets
sd0 at scsibus1 targ 0 lun 0: <ATA, VBOX HARDDISK, 1.0> SCSI3 0/direct fixed t10.ATA_VBOX_HARDDISK_VB36de
2a1b-bdd5b9f2_
sd0: 1806MB, 512 bytes/sector, 3700000 sectors
isa0 at pcib0
com0 at isa0 port 0x3f8/8 irq 4: ns16550a, 16 byte fifo
com0: console
pckbc0 at isa0 port 0x60/5
pckbd0 at pckbc0 (kbd slot)
pckbc0: using irq 1 for kbd slot
wskbd0 at pckbd0: console keyboard, using wsdisplay0
pms0 at pckbc0 (aux slot)
pckbc0: using irq 12 for aux slot
wsmouse0 at pms0 mux 0
pcppi0 at isa0 port 0x61
spkr0 at pcppi0
npx0 at isa0 port 0xf0/16: reported by CPUID; using exception 16
vscsi0 at root
scsibus2 at vscsi0: 256 targets
softraid0 at root
scsibus3 at softraid0: 256 targets
root on rd0a swap on rd0b dump on rd0b
Process (pid 1) got signal 11
Process (pid 1) got signal 11
Process (pid 1) got signal 11
Process (pid 1) got signal 11
Process (pid 1) got signal 11
...

For kicks I tried rolling back to 9c7bf4a24d92533ea748f9ce36792e59508323aa (prior to the latest kernel config strip), but no change.

**Comment by bconway** [comment]
I can also send up the image (about 300 MB before compression) and pass that along, if it would be helpful.

**Comment by yellowman** [comment]
Did this happen on the 201502something snapshot?

**Comment by bconway** [comment]
Haven't used any snapshots other than the one I used to boostrap OPENBSD_5_7, and have rebuilt it 3 or 4 times since then.

**Comment by bconway** [comment]
Did some further testing, I get the same result with the 5.7 i386 com0 image from http://www.nmedia.net/flashrd/images/20150320/ .

I fired up my 5.6-stable build and flashrd image VMs and both still run fine, so I don't think this is something that VirtualBox has broken in recent updates (but anything's possible).

**Comment by bconway** [comment]
Had some time to research further. I tried out the amd64 images from the nmedia.net link above in the same VBox configuration and had **no issues**, it booted perfectly.

Going back to i386, I played around with some config.strip options as well as twiddling ${blocks} from 4600 and the NKPTP kernel option, but found no differences. So not much help there.

**Comment by bconway** [comment]
I did some rooting around further, it looks like the kcopy being generated by the mkrdroot phase is broken, all named versions of the executable segfault:

```
root:buildi386:0:mkrdrootcg.yFJXv1# ls
Makefile             init.lo              ksh_stub.c           mount_stub.o         reboot.lo
cp.lo                init_stub.c          ksh_stub.o           mount_vnd.lo         reboot_stub.c
cp_stub.c            init_stub.o          ls.lo                mount_vnd_stub.c     reboot_stub.o
cp_stub.o            kcopy*               ls_stub.c            mount_vnd_stub.o     umount.lo
fsck.lo              kcopy.c              ls_stub.o            mv.lo                umount_stub.c
fsck_ffs.lo          kcopy.cache          mount.lo             mv_stub.c            umount_stub.o
fsck_ffs_stub.c      kcopy.conf           mount_ffs.lo         mv_stub.o
fsck_ffs_stub.o      kcopy.core           mount_ffs_stub.c     pax.lo
fsck_stub.c          kcopy.o              mount_ffs_stub.o     pax_stub.c
fsck_stub.o          ksh.lo               mount_stub.c         pax_stub.o
root:buildi386:0:mkrdrootcg.yFJXv1# ./kcopy
Usage: kcopy <prog> <args> ..., where <prog> is one of:
 ksh -sh sh pax tar ls fsck fsck_ffs reboot init mount mount_ffs mount_vnd
 vnconfig umount cp mv kcopy
root:buildi386:1:mkrdrootcg.yFJXv1# ./kcopy ls
Segmentation fault (core dumped)
root:buildi386:139:mkrdrootcg.yFJXv1# ./kcopy pax
Segmentation fault (core dumped)
```

I made a simpler test case that consisted of only `ls`, and even that core dumped. I don't currently have an amd64 build system set up to compare it to, but I assume it's working fine there.

Compared to my 5.6 i386 build system, the Makefile generated by crunchgen is identical other than the top comment. Perhaps there is a wider issue with crunchgen on 5.7 i386?

**Comment by yellowman** [comment]
Yeah I kinda thought that might be the case. I wonder if -nopie or -pie or some flag like that helps?

**Comment by bconway** [comment]
Yeah, I was thinking that and tried flipping them in the Makefile without much change. I'm finishing up my amd64 build system for comparison and then sending off a simplified test case to -misc for input.
