### ISSUE TITLE
Document references no-longer-available tarball

### ISSUE THREAD

**Issue by bklang** [yellowman/flashrd#37]
I apologize if this is the wrong place to report this. I was going to send a pull request, but I don't think the website docs live on Github.

The installation docs for FlashRD reference a `miscXX.tgz`, which appears to no longer exist since OpenBSD 5.5. Page in question is here: http://www.nmedia.net/flashrd/install.html

**Comment by bconway** [comment]
It should probably also mention that etcXX.tgz is now in usr/share/sysmerge/etc.tgz of the unpacked baseXX.tgz. Same for xetc.tgz.

**Comment by bklang** [comment]
One other documentation update: it appears that the call to invoke `rc.flashrd.conf` has been moved from `/etc/rc.conf.local` to `/etc/rc`. If so, perhaps the note to include that in a custom `rc.conf.local` should be removed from http://www.nmedia.net/flashrd/flashrd-faq.html ?

**Comment by yellowman** [comment]
Ok I improved these two documentation areas.

Please send further updates as diffs :)
