### ISSUE TITLE
OpenBSD 6.0 will remove tmpfs support

### ISSUE THREAD

**Issue by siepkes** [yellowman/flashrd#46]
OpenBSD 6.0 will remove tmpfs support, see: https://www.openbsd.org/plus60.html under "Disable tmpfs.". The reason being it apparently not being maintained anymore. tmpfs is currently being used to create filesystems for /var and /tmp.

An alternative might be to use mount_mfs: http://man.openbsd.org/OpenBSD-current/man8/newfs.8

**Comment by yellowman** [comment]
Since flashrd recompiles the kernel for you, the flashrd 2.1 can turn on option TMPFS.

It is disabled in the tree but won't be removed quite yet. People like the idea of something smarter/faster than mfs, and tmpfs, if care is given, is still considered a good potential replacement.
