### ISSUE TITLE
mtree in OpenBSD 6.1 dont have user uucp anymore

### ISSUE THREAD

**Issue by khorsmann** [yellowman/flashrd#52]
I saw the error "dont find user uucp" on boot my flashrd 2.0 OpenBSD 6.1 box.
Have not an nice idea to fix mtree for 6.1 and below.
 
       # ./var/spool/lock
        lock                    uname=root gname=dialer mode=1775
        ..
        output
            lpd                 gname=daemon mode=0775
            ..
        ..

$ less /etc/mtree/4.4BSD.dist
$ uname -ra
OpenBSD openbsd61.0x300.de 6.1 GENERIC.MP#0 i386

**Comment by bobbisanchez** [comment]
maybe this diff works for OpenBSD6.5 amd64 i am still on testing ...
[mtree.flashrd-openbsd65.diff.txt](https://github.com/yellowman/flashrd/files/3204580/mtree.flashrd-openbsd65.diff.txt)



```
94d93
< 
97,98d95
< 
<         # ./var/spool/ftp
106,107d102
<             #pub		mode=0555
<             #..
111c106
<         lock			uname=uucp gname=dialer mode=1775
---
>         lock			uname=root gname=dialer mode=1775
113c108,110
<         output			gname=daemon mode=0775
---
>         output
>             lpd			gname=daemon mode=0775
> 	    ..
114a112,113
> 
>         # ./var/spool/smtpd
115a115,126
>             corrupt		type=dir uname=_smtpq gname=wheel mode=0700
>             ..
>             incoming		type=dir uname=_smtpq gname=wheel mode=0700
>             ..
>             offline		type=dir uname=root gname=_smtpq mode=0770
>             ..
>             purge		type=dir uname=_smtpq gname=wheel mode=0700
>             ..
>             queue		type=dir uname=_smtpq gname=wheel mode=0700
>             ..
>             temporary		type=dir uname=_smtpq gname=wheel mode=0700
>             ..
117,122c128
<         #sockets		mode=777
<         #..
<         uucp			uname=uucp gname=daemon
<         ..
<         uucppublic		uname=uucp gname=daemon mode=0755
<         ..
---
> 
```

**Comment by bobbisanchez** [comment]
maybe this patch (attached file)
[patch-mtree-for-openbsb65-amd.patch.txt](https://github.com/yellowman/flashrd/files/3204673/patch-mtree-for-openbsb65-amd.patch.txt)
 will work, i am still on testing under OpenBSD65 amd64

**Comment by khorsmann** [comment]
@bobbisanchez I switched from flashrd to resflash. It's maintained and don't need builded kernel. https://stable.rcesoftware.com/resflash/

**Comment by yellowman** [comment]
Karsten Horsmann [notifications@github.com] wrote:
> @bobbisanchez I switched from flashrd to resflash. It's maintained and don't need builded kernel. https://stable.rcesoftware.com/resflash/
> 

Yes, resflash is a good replacement if you don't want a custom kernel.
